### Importing libraries

In [1]:
import numpy as np
import pandas as pd
import random
import math

from sklearn import preprocessing # normalization library


### Robot Data
Pioneer 3dx

In [3]:

LMr=381e-3
R=195e-3

v_max= 1
v_min=0.5

Lt_max=1.2
Lt_min=0.3

### Obstacle circle 

Sensor range data: $[dmin_1\quad dmax_1]\quad m$ 

Heading angle data: $[-\pi\quad\pi]\quad rad$ 


In [4]:
min_d1=0.3
max_d1=1

In [5]:
# Sensor Data gen 
Obs_Data=[round(random.uniform(min_d1, max_d1),4) for _ in range(3000*3)]
Obs_Data_M=np.array(Obs_Data).reshape(3000,3)

print('Raw data :',Obs_Data_M[:2,:])

normalizer=preprocessing.MinMaxScaler()
Obs_Data_Norm=normalizer.fit_transform(Obs_Data_M)
print('Normalized data :',Obs_Data_Norm[:2,:])


Raw data : [[0.562  0.8656 0.6433]
 [0.6864 0.6097 0.8191]]
Normalized data : [[0.37421384 0.80820938 0.49042584]
 [0.55202973 0.44221968 0.74164047]]


In [6]:
# HA data gen

HA_Data=[round(random.uniform(-math.pi, math.pi),4) for _ in range(3000)]
HA_Data=np.array(HA_Data).reshape(3000,1)
print('Angle data :',HA_Data[:2])

Angle data : [[-1.1116]
 [-0.0755]]


In [23]:
C1_Normal_Data=np.hstack((Obs_Data_Norm,HA_Data))

### Special Data for small angles and near obstacle

In [22]:
Obs_Data_Near=[round(random.uniform(min_d1,max_d1-0.6),4) for _ in range(1000*3)]
Obs_Data_M_Near=np.array(Obs_Data_Near).reshape(1000,3)

print('Raw data :',Obs_Data_M_Near[:2,:])


Norm_Near=normalizer.fit(Obs_Data_M)
Obs_Data_Near=Norm_Near.transform(Obs_Data_M_Near)

print('Normalized data :',Obs_Data_Near[:2,:])


Raw data : [[0.3413 0.3263 0.3922]
 [0.383  0.301  0.3892]]
Normalized data : [[0.05874786 0.03689931 0.13160903]
 [0.11835334 0.0007151  0.12732209]]


Small angles

In [37]:
Small_Theta_Data=[round(random.uniform(-0.5, 0.5),4) for _ in range(1000)]
Small_Theta_Array=np.array(Small_Theta_Data).reshape(1000,1)
print('Angle data :',Small_Theta_Array[:2])

Angle data : [[-0.481 ]
 [ 0.0463]]


Stack small

In [ ]:
# Stack All

St_train_C1=np.hstack((Obs_Data_Norm,HA_Data))



### Inverse Kinematic Model

$$\omega_{R/L}=\left( 1\pm\frac{L_{MR}}{2L_T}\right)\frac{v}{R}$$

Fist Case: Left sensor nearest, objective angle +

In [8]:
odp=0.3
tethad=3
S=-1
Lt_p=round((odp*(Lt_max-Lt_min)+Lt_min),4)
print('Ltp: ',Lt_p)
V_p=round(((odp)*(v_max-v_min)+v_min),4)
print('vel: ',V_p)
W_R=round((1+((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
W_L=round((1-((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
print('Right Wheel vel: ',W_R)
print('Left Wheel vel: ',W_L)

Ltp:  0.57
vel:  0.65
Right Wheel vel:  -0.0088
Left Wheel vel:  6.6754


Second Case: Left sensor nearest, objective angle -

In [ ]:

odp=0.1
tethad=-3
S=0.5
Lt_p=round((odp*(Lt_max-Lt_min)+Lt_min),4)
print('Ltp: ',Lt_p)
V_p=round(((odp)*(v_max-v_min)+v_min),4)
print('vel: ',V_p)
W_R=round((1+((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
W_L=round((1-((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
print('Right Wheel vel: ',W_R)
print('Left Wheel vel: ',W_L)

Third case: Right sensor nearest, objective angle +

In [ ]:
odp=0.114049
tethad=0.3
S=0.5
Lt_p=round((odp*(Lt_max-Lt_min)+Lt_min),4)
print('Ltp: ',Lt_p)
V_p=round(((odp)*(v_max-v_min)+v_min),4)
print('vel: ',V_p)
W_R=round((1+((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
W_L=round((1-((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
print('Right Wheel vel: ',W_R)
print('Left Wheel vel: ',W_L)

Fourth case: Right sensor nearest, objective angle -

In [ ]:
odp=0.209947
tethad=-1.6546
S=-1
Lt_p=round((odp*(Lt_max-Lt_min)+Lt_min),4)
print('Ltp: ',Lt_p)
V_p=round(((odp)*(v_max-v_min)+v_min),4)
print('vel: ',V_p)
W_R=round((1+((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
W_L=round((1-((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
print('Right Wheel vel: ',W_R)
print('Left Wheel vel: ',W_L)

Fifth case: Front sensor nearest, objective angle +

In [ ]:
odp=0.01
tethad=0.3
S=-1
Lt_p=round((odp*(Lt_max-Lt_min)+Lt_min),4)
print('Ltp: ',Lt_p)
V_p=round(((odp)*(v_max-v_min)+v_min),4)
print('vel: ',V_p)
W_R=round((1+((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
W_L=round((1-((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
print('Right Wheel vel: ',W_R)
print('Left Wheel vel: ',W_L)

Sixth case: Front sensor nearest, objective angle -

In [ ]:
odp=0.01
tethad=-3
S=-1
Lt_p=round((odp*(Lt_max-Lt_min)+Lt_min),4)
print('Ltp: ',Lt_p)
V_p=round(((odp)*(v_max-v_min)+v_min),4)
print('vel: ',V_p)
W_R=round((1+((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
W_L=round((1-((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
print('Right Wheel vel: ',W_R)
print('Left Wheel vel: ',W_L)

### Dataset Creation

In [ ]:
Df_C1['Min Value']=Df_C1[['LD','FD','RD']].min(axis=1)
Df_C1.sample(6)


### Left Wheel Evaluation

In [ ]:
def lw_eval(df):
    if df['Min Value']== df['LD'] and df['HA']>0:
        Sf=-1
        odpf=df['LD']
    elif df['Min Value']== df['LD'] and df['HA']<0:
        Sf=0.5
        odpf=df['LD']
    elif df['Min Value']== df['RD'] and df['HA']>0:
        Sf=0.5
        odpf=df['RD']
    elif df['Min Value']== df['RD'] and df['HA']<0:
        Sf=-1
        odpf=df['RD']
    elif df['Min Value']== df['FD'] and df['HA']>0:
        Sf=-1
        odpf=df['FD']
    elif df['Min Value']== df['FD'] and df['HA']<0:
        Sf=-1
        odpf=df['FD']
    
        
      
    if odpf==0:
      odpf=0.001
      
    tethad=df['HA']
    
    
    Lt_p=round((odpf*(Lt_max-Lt_min)+Lt_min),4)
    V_p=round(((odpf)*(v_max-v_min)+v_min),4)

    
    return round((1-((LMr*tethad*Sf)/(2*Lt_p)))*(V_p/R),4)

def rw_eval(df):
    if df['Min Value']== df['LD'] and df['HA']>0:
        Sf=-1
        odpf=df['LD']
    elif df['Min Value']== df['LD'] and df['HA']<0:
        Sf=0.5
        odpf=df['LD']
    elif df['Min Value']== df['RD'] and df['HA']>0:
        Sf=0.5
        odpf=df['RD']
    elif df['Min Value']== df['RD'] and df['HA']<0:
        Sf=-1
        odpf=df['RD']
    elif df['Min Value']== df['FD'] and df['HA']>0:
        Sf=-1
        odpf=df['FD']
    elif df['Min Value']== df['FD'] and df['HA']<0:
        Sf=-1
        odpf=df['FD']
      
      
    if odpf==0:
      odpf=0.001
      
    tethad=df['HA']
   
    
    Lt_p=round((odpf*(Lt_max-Lt_min)+Lt_min),4)
    V_p=round(((odpf)*(v_max-v_min)+v_min),4)

    
    return round((1+((LMr*tethad*Sf)/(2*Lt_p)))*(V_p/R),4)
        

Df_C1=Df_C1.assign(W_L=Df_C1.apply(lw_eval,axis=1))

Df_C1=Df_C1.assign(W_R=Df_C1.apply(rw_eval,axis=1))

Df_C1.sample(6)



        

Extract WL to train 

In [ ]:
Df_C1_Train=Df_C1[['LD','FD','RD','HA','W_L']]
Df_C1_Train.sample(6)

In [ ]:
Df_C1_Train.to_csv('Df_C1_Train_L_2.csv',index=False)

Extract WR to train 

In [ ]:
Df_C1_TrainR=Df_C1[['LD','FD','RD','HA','W_R']]
Df_C1_TrainR.sample(6)

In [ ]:
Df_C1_TrainR.to_csv('Df_C1_Train_R_2.csv',index=False)

## No obstacle circle

### Angle Data Generation

In [ ]:
HA_Data_2=[round(random.uniform(-math.pi, math.pi),4) for _ in range(3000)]
HA_Data_2=np.array(HA_Data).reshape(3000,1)
print('Angle data :',HA_Data_2[:2])

In [ ]:
Df_C2=pd.DataFrame(HA_Data_2,columns=[['HA']])
Df_C2.sample(6)

### Evaluation   Right and Left Wheel

In [ ]:
Lt_2=1.2
v_max=1

def lw_eval_NO(df):
    Sf1=-1
    haf=df['HA']
    Lt_pf=round((Lt_2),4)
    V_pf=round(v_max,4)
    return round((1-((LMr*haf*Sf1)/(2*Lt_pf)))*(V_pf/R),4)

def rw_eval_NO(df):
    Sf1=-1
    haf=df['HA']
    Lt_pf=round((Lt_2),4)
    V_pf=round(v_max,4)
    return round((1+((LMr*haf*Sf1)/(2*Lt_pf)))*(V_pf/R),4)


Df_C2=Df_C2.assign(W_L=Df_C2.apply(lw_eval_NO,axis=1))

Df_C2=Df_C2.assign(W_R=Df_C2.apply(rw_eval_NO,axis=1))


Df_C2.sample(6)



Left Wheel Train NO

In [ ]:
Df_C2_Train=Df_C2[['HA','W_L']]
Df_C2_Train.sample(6)

In [ ]:
Df_C2_Train.to_csv('Df_C2_Train_L_2.csv',index=False)

Right Wheel Train NO

In [ ]:
Df_C2_Train_R=Df_C2[['HA','W_R']]
Df_C2_Train_R.head(6)

In [ ]:
Df_C2_Train_R.to_csv('Df_C2_Train_R_2.csv',index=False)