### Importing libraries

In [46]:
import numpy as np
import pandas as pd
import random
import math

from sklearn import preprocessing # normalization library


### Robot Data
Pioneer 3dx

In [47]:

LMr=381e-3
R=195e-3

v_max= 1
v_min=0.5

Lt_max=1.2
Lt_min=0.3

### Obstacle circle 

Sensor range data: $[dmin_1\quad dmax_1]\quad m$ 

Heading angle data: $[-\pi\quad\pi]\quad rad$ 


In [48]:
min_d1=0.3
max_d1=1

In [49]:
# Sensor Data gen 
Obs_Data=[round(random.uniform(min_d1, max_d1),4) for _ in range(3000*3)]
Obs_Data_M=np.array(Obs_Data).reshape(3000,3)

print('Raw data :',Obs_Data_M[:2,:])

normalizer=preprocessing.MinMaxScaler()
Obs_Data_Norm=normalizer.fit_transform(Obs_Data_M)
print('Normalized data :',Obs_Data_Norm[:2,:])


Raw data : [[0.9095 0.9062 0.8226]
 [0.3276 0.672  0.4375]]
Normalized data : [[0.8707833  0.8661046  0.74674861]
 [0.0390223  0.53143755 0.19636987]]


In [50]:
# HA data gen

HA_Data=[round(random.uniform(-math.pi, math.pi),4) for _ in range(3000)]
HA_Data=np.array(HA_Data).reshape(3000,1)
print('Angle data :',HA_Data[:2])

Angle data : [[1.6087]
 [2.8994]]


Stack Normal Data

In [51]:


C1_Normal_Data=np.hstack((Obs_Data_Norm,HA_Data))
print('Normal array :',C1_Normal_Data[:2])

Normal array : [[0.8707833  0.8661046  0.74674861 1.6087    ]
 [0.0390223  0.53143755 0.19636987 2.8994    ]]


### Special Data for small angles and near obstacle

In [54]:
Obs_Data_Near=[round(random.uniform(min_d1,max_d1-0.6),4) for _ in range(1000*3)]
Obs_Data_M_Near=np.array(Obs_Data_Near).reshape(1000,3)

print('Raw data :',Obs_Data_M_Near[:2,:])


Norm_Near=normalizer.fit(Obs_Data_M)
Obs_Data_Near=Norm_Near.transform(Obs_Data_M_Near)

print('Normalized data :',Obs_Data_Near[:2,:])


Raw data : [[0.3602 0.3771 0.383 ]
 [0.3725 0.3569 0.3098]]
Normalized data : [[0.08562035 0.11003144 0.11847935]
 [0.10320183 0.08116605 0.01386308]]


Small angles

In [55]:
Small_Theta_Data=[round(random.uniform(-0.5, 0.5),4) for _ in range(1000)]
Small_Theta_Array=np.array(Small_Theta_Data).reshape(1000,1)
print('Angle data :',Small_Theta_Array[:2])

Angle data : [[-0.1556]
 [-0.4836]]


Stack small

In [56]:
C1_Small_Data=np.hstack((Obs_Data_Near,Small_Theta_Array))
print('Small array :',C1_Small_Data[:2])

Small array : [[ 0.08562035  0.11003144  0.11847935 -0.1556    ]
 [ 0.10320183  0.08116605  0.01386308 -0.4836    ]]


Stack all and Randomize

In [70]:
# Stack All

St_train_C1=np.vstack((C1_Normal_Data,C1_Small_Data))
np.random.shuffle(St_train_C1)
print(St_train_C1[:2])



[[ 0.00343053  0.24707059  0.54752037 -0.8136    ]
 [ 0.1598056   0.60245785  0.77733314  2.8288    ]]


### Inverse Kinematic Model

$$\omega_{R/L}=\left( 1\pm\frac{L_{MR}}{2L_T}\right)\frac{v}{R}$$

Fist Case: Left sensor nearest, objective angle +

In [8]:
odp=0.3
tethad=3
S=-1
Lt_p=round((odp*(Lt_max-Lt_min)+Lt_min),4)
print('Ltp: ',Lt_p)
V_p=round(((odp)*(v_max-v_min)+v_min),4)
print('vel: ',V_p)
W_R=round((1+((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
W_L=round((1-((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
print('Right Wheel vel: ',W_R)
print('Left Wheel vel: ',W_L)

Ltp:  0.57
vel:  0.65
Right Wheel vel:  -0.0088
Left Wheel vel:  6.6754


Second Case: Left sensor nearest, objective angle -

In [ ]:

odp=0.1
tethad=-3
S=0.5
Lt_p=round((odp*(Lt_max-Lt_min)+Lt_min),4)
print('Ltp: ',Lt_p)
V_p=round(((odp)*(v_max-v_min)+v_min),4)
print('vel: ',V_p)
W_R=round((1+((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
W_L=round((1-((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
print('Right Wheel vel: ',W_R)
print('Left Wheel vel: ',W_L)

Third case: Right sensor nearest, objective angle +

In [ ]:
odp=0.114049
tethad=0.3
S=0.5
Lt_p=round((odp*(Lt_max-Lt_min)+Lt_min),4)
print('Ltp: ',Lt_p)
V_p=round(((odp)*(v_max-v_min)+v_min),4)
print('vel: ',V_p)
W_R=round((1+((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
W_L=round((1-((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
print('Right Wheel vel: ',W_R)
print('Left Wheel vel: ',W_L)

Fourth case: Right sensor nearest, objective angle -

In [ ]:
odp=0.209947
tethad=-1.6546
S=-1
Lt_p=round((odp*(Lt_max-Lt_min)+Lt_min),4)
print('Ltp: ',Lt_p)
V_p=round(((odp)*(v_max-v_min)+v_min),4)
print('vel: ',V_p)
W_R=round((1+((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
W_L=round((1-((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
print('Right Wheel vel: ',W_R)
print('Left Wheel vel: ',W_L)

Fifth case: Front sensor nearest, objective angle +

In [ ]:
odp=0.01
tethad=0.3
S=-1
Lt_p=round((odp*(Lt_max-Lt_min)+Lt_min),4)
print('Ltp: ',Lt_p)
V_p=round(((odp)*(v_max-v_min)+v_min),4)
print('vel: ',V_p)
W_R=round((1+((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
W_L=round((1-((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
print('Right Wheel vel: ',W_R)
print('Left Wheel vel: ',W_L)

Sixth case: Front sensor nearest, objective angle -

In [ ]:
odp=0.01
tethad=-3
S=-1
Lt_p=round((odp*(Lt_max-Lt_min)+Lt_min),4)
print('Ltp: ',Lt_p)
V_p=round(((odp)*(v_max-v_min)+v_min),4)
print('vel: ',V_p)
W_R=round((1+((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
W_L=round((1-((LMr*tethad*S)/(2*Lt_p)))*(V_p/R),4)
print('Right Wheel vel: ',W_R)
print('Left Wheel vel: ',W_L)

### Dataset Creation

In [ ]:
Df_C1['Min Value']=Df_C1[['LD','FD','RD']].min(axis=1)
Df_C1.sample(6)


### Left Wheel Evaluation

In [ ]:
def lw_eval(df):
    if df['Min Value']== df['LD'] and df['HA']>0:
        Sf=-1
        odpf=df['LD']
    elif df['Min Value']== df['LD'] and df['HA']<0:
        Sf=0.5
        odpf=df['LD']
    elif df['Min Value']== df['RD'] and df['HA']>0:
        Sf=0.5
        odpf=df['RD']
    elif df['Min Value']== df['RD'] and df['HA']<0:
        Sf=-1
        odpf=df['RD']
    elif df['Min Value']== df['FD'] and df['HA']>0:
        Sf=-1
        odpf=df['FD']
    elif df['Min Value']== df['FD'] and df['HA']<0:
        Sf=-1
        odpf=df['FD']
    
        
      
    if odpf==0:
      odpf=0.001
      
    tethad=df['HA']
    
    
    Lt_p=round((odpf*(Lt_max-Lt_min)+Lt_min),4)
    V_p=round(((odpf)*(v_max-v_min)+v_min),4)

    
    return round((1-((LMr*tethad*Sf)/(2*Lt_p)))*(V_p/R),4)

def rw_eval(df):
    if df['Min Value']== df['LD'] and df['HA']>0:
        Sf=-1
        odpf=df['LD']
    elif df['Min Value']== df['LD'] and df['HA']<0:
        Sf=0.5
        odpf=df['LD']
    elif df['Min Value']== df['RD'] and df['HA']>0:
        Sf=0.5
        odpf=df['RD']
    elif df['Min Value']== df['RD'] and df['HA']<0:
        Sf=-1
        odpf=df['RD']
    elif df['Min Value']== df['FD'] and df['HA']>0:
        Sf=-1
        odpf=df['FD']
    elif df['Min Value']== df['FD'] and df['HA']<0:
        Sf=-1
        odpf=df['FD']
      
      
    if odpf==0:
      odpf=0.001
      
    tethad=df['HA']
   
    
    Lt_p=round((odpf*(Lt_max-Lt_min)+Lt_min),4)
    V_p=round(((odpf)*(v_max-v_min)+v_min),4)

    
    return round((1+((LMr*tethad*Sf)/(2*Lt_p)))*(V_p/R),4)
        

Df_C1=Df_C1.assign(W_L=Df_C1.apply(lw_eval,axis=1))

Df_C1=Df_C1.assign(W_R=Df_C1.apply(rw_eval,axis=1))

Df_C1.sample(6)



        

Extract WL to train 

In [ ]:
Df_C1_Train=Df_C1[['LD','FD','RD','HA','W_L']]
Df_C1_Train.sample(6)

In [ ]:
Df_C1_Train.to_csv('Df_C1_Train_L_2.csv',index=False)

Extract WR to train 

In [ ]:
Df_C1_TrainR=Df_C1[['LD','FD','RD','HA','W_R']]
Df_C1_TrainR.sample(6)

In [ ]:
Df_C1_TrainR.to_csv('Df_C1_Train_R_2.csv',index=False)

## No obstacle circle

### Angle Data Generation

In [ ]:
HA_Data_2=[round(random.uniform(-math.pi, math.pi),4) for _ in range(3000)]
HA_Data_2=np.array(HA_Data).reshape(3000,1)
print('Angle data :',HA_Data_2[:2])

In [ ]:
Df_C2=pd.DataFrame(HA_Data_2,columns=[['HA']])
Df_C2.sample(6)

### Evaluation   Right and Left Wheel

In [ ]:
Lt_2=1.2
v_max=1

def lw_eval_NO(df):
    Sf1=-1
    haf=df['HA']
    Lt_pf=round((Lt_2),4)
    V_pf=round(v_max,4)
    return round((1-((LMr*haf*Sf1)/(2*Lt_pf)))*(V_pf/R),4)

def rw_eval_NO(df):
    Sf1=-1
    haf=df['HA']
    Lt_pf=round((Lt_2),4)
    V_pf=round(v_max,4)
    return round((1+((LMr*haf*Sf1)/(2*Lt_pf)))*(V_pf/R),4)


Df_C2=Df_C2.assign(W_L=Df_C2.apply(lw_eval_NO,axis=1))

Df_C2=Df_C2.assign(W_R=Df_C2.apply(rw_eval_NO,axis=1))


Df_C2.sample(6)



Left Wheel Train NO

In [ ]:
Df_C2_Train=Df_C2[['HA','W_L']]
Df_C2_Train.sample(6)

In [ ]:
Df_C2_Train.to_csv('Df_C2_Train_L_2.csv',index=False)

Right Wheel Train NO

In [ ]:
Df_C2_Train_R=Df_C2[['HA','W_R']]
Df_C2_Train_R.head(6)

In [ ]:
Df_C2_Train_R.to_csv('Df_C2_Train_R_2.csv',index=False)